### ISSUE TITLE
as part of the generated .zip/git repo, create a file with relevant metadata

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-planning#110]
In a discussion with @cmoulliard, we came up with an idea: the Launcher could generate, in the root directory of the .zip / Git repo, a file called e.g. `.launched-from` (or `.launcher-metadata`, or whatever). This file would contain relevant metadata to how the .zip / Git repo was generated: parameters selected in the wizard, the original booster Git repo and tag, etc. It would be useful when reporting a booster issue. Format of the file could be YAML, JSON, Java properties, etc.

**Comment by cmoulliard** [comment]
As the S2I Build process relies on a specific version of the openjdk-1.8 docker image [1], then such version info should also be included within that file. 

This number should come from one of the following resource 
- Openshift Template - within the imageStream

```
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2-7
```

- Fabric8 Maven Plugin - parameter  (! the booster parent doesn't include it yet [2])

```
<fabric8.generator.from>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift</fabric8.generator.from>
```

[1] https://access.redhat.com/containers/?tab=security#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift/images/1.2-7
[2] https://github.com/openshiftio/booster-parent/blob/master/pom.xml#L60
