### ISSUE TITLE
Boosters Jenkinsfile issuing oc policy add-role-to-user view will fail

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-planning#8]
Boosters where the Jenkinsfile issues an "oc policy add-role-to-user view" will fail 

```
stage("Prepare") {
    sh "oc policy add-role-to-user view -z default"
  }
```
and will report this error

```
[Pipeline] stage
[Pipeline] { (Prepare)
[Pipeline] sh
[vertx-cm-vertx-cm] Running shell script
++ oc project -q
error: no project has been set
+ oc policy add-role-to-user view -n -z default
Error from server: User "system:serviceaccount:vertx-cm:jenkins" cannot get policybindings in project "vertx-cm"
```

This problem comes from the fact that when Jenkins creates the job and log to openshift, it will use as user the token of the service account

```
+ oc whoami
system:serviceaccount:vertx-cm:jenkins
[Pipeline] sh
[vertx-cm-vertx-cm] Running shell script
+ oc policy add-role-to-user view -z default
Error from server: User "system:serviceaccount:vertx-cm:jenkins" cannot get policybindings in project "vertx-cm"
```

A solution to be investigated is : 
- Give more rights to the serviceaccount
- Log on using the user

```
stage("Prepare") {
    sh "oc login https://192.168.64.25:8443 -u developer -p developer --insecure-skip-tls-verify"
    sh "oc project \$(oc project -q)"
    sh "oc policy add-role-to-user view -z default"
  }
```

Even if we apply the workaround mentioned, the docker container of the runtime created will also complain that it doesn't have the correct permission

```
Apr 11, 2017 2:55:07 PM io.vertx.config.impl.ConfigRetrieverImpl
SEVERE: Error while scanning configuration
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/demo/configmaps/vertx-http-configmap. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:319)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:685)
```

**Comment by ALRubinger** [comment]
@cmoulliard Who is to be assigned to chase this down?

**Comment by cmoulliard** [comment]
@ALRubinger Maybe a Fabric8 guy as James Rawling knows the answer.

**Comment by alesj** [comment]
@luksa or @rawlingsj ^^ can one of you guys have a look at this, as suggest what can be done ...

**Comment by cmoulliard** [comment]
> This problem comes from the fact that when Jenkins creates the job and log to openshift, it will use as user the token of the service account

The solution is to use the `edit` role which is assigned to the role of the jenkins user

```
  stage("Prepare") {
    sh "oc policy add-role-to-user edit -z default"
  }
```

**Comment by luksa** [comment]
Not sure what you're trying to achieve, but:
- do not try logging in with a regular user; serviceaccounts are what's meant to be used by "services" (apps running in pods)
- if the serviceaccount you're using needs elevated permissions, the person deploying the app needs to elevate them using oc policy add-role-to-user (the serviceaccount obviously can't elevate its own permissions).

**Comment by cmoulliard** [comment]
@luksa You are right. I think that this "oc command" is issued at the wrong place within the jenkins file as this role `view` is required by the pod/container starting the vert.x/swarm/spring boot runtime

**Comment by cmoulliard** [comment]
Question : Is it the responsibility of the jenkins pipeline to create the serviceAccount, rolebinding and assign the ServiceAccount to the DeploymentConfig of the pod to be created vs using Fabric8 yaml files to create such objects ?

**Comment by rawlingsj** [comment]
@cmoulliard yeah it's the same thing that I mentioned on IRC earlier.  Jenkins needs a serviceaccount and you apply rolebindings, so that jenkins has karma to interact with OpenShift.  

Here's the devtools jenkins-openshift image with it's edit rolebinding (needed to create build pods) https://github.com/fabric8io/fabric8-team-components/blob/master/jenkins-openshift/src/main/fabric8/jenkins-edit-rb.yml

**Comment by cmoulliard** [comment]
@rawlingsj What is the benefit to have a RoleRef : jenkins

Our rolebinding is defined to use the `edit` role too 

```
oc get rolebinding/jenkins_edit -o yaml
apiVersion: v1
kind: RoleBinding
metadata:
  labels:
    template: jenkins-ephemeral-template
  name: jenkins_edit
  namespace: sb-configmap
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: sb-configmap
userNames:
- system:serviceaccount:sb-configmap:jenkins

oc get serviceaccount/jenkins -o yaml
apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-kzm6a
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
  labels:
    template: jenkins-ephemeral-template
  name: jenkins
  namespace: sb-configmap
secrets:
- name: jenkins-token-ngx6o
- name: jenkins-dockercfg-kzm6a

oc get dc/jenkins -o yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    template: jenkins-ephemeral-template
  name: jenkins
  namespace: sb-configmap
spec:
  replicas: 1
  selector:
    name: jenkins
  strategy:
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: jenkins
    spec:
      containers:
      - env:
        - name: OPENSHIFT_ENABLE_OAUTH
          value: "true"
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true"
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default:443
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: JNLP_SERVICE_NAME
          value: jenkins-jnlp
        image: openshift/jenkins-2-centos7@sha256:3af07ffa6115387e74d2c866ab19889ca2ef59c77d6f9eb8888ac32718d5773b
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: jenkins
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: jenkins-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
...
```
